In [1]:
import numpy as np

In [252]:
# this should get 0.33
y = np.asarray([[0,1,0],[1,0,0],[0,0,1],[0,0,1]]).astype("float32")
py = np.asarray([[0,1,0],[1,0,0],[1,0,0],[1,0,0]]).astype("float32")

In [253]:
# this should get 1.0
y = np.asarray([[0,1,0],[1,0,0],[0,0,1],[0,0,1]]).astype("float32")
py = np.asarray([[0,1,0],[1,0,0],[0,0,1],[0,0,1]]).astype("float32")

In [280]:
# should be 0.273
y = np.asarray([[0,0,1],[1,0,0],[0,0,1],[0,0,1]]).astype("float32")
py = np.asarray([[0,1,0],[1,0,0],[1,0,0],[0,0,1]]).astype("float32")

In [281]:
y

array([[ 0.,  0.,  1.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.],
       [ 0.,  0.,  1.]], dtype=float32)

In [282]:
py

array([[ 0.,  1.,  0.],
       [ 1.,  0.,  0.],
       [ 1.,  0.,  0.],
       [ 0.,  0.,  1.]], dtype=float32)

In [283]:
po = np.dot(y.T, py)
print po
po = po / np.sum(po)
print po

[[ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]
[[ 0.25  0.    0.  ]
 [ 0.    0.    0.  ]
 [ 0.25  0.25  0.25]]


In [293]:
np.dot(po.sum(axis=1), po.sum(axis=0))

0.3125

In [294]:
(np.trace(po) - np.dot(po.sum(axis=1), po.sum(axis=0))) / (1 - np.dot(po.sum(axis=1), po.sum(axis=0)))

0.27272727272727271

----------

In [266]:
w = np.ones((3,3))
w[0,0]=0
w[1,1]=0
w[2,2]=0
w

array([[ 0.,  1.,  1.],
       [ 1.,  0.,  1.],
       [ 1.,  1.,  0.]])

In [267]:
numerator = np.dot(y.T, py)
print numerator

[[ 1.  0.  0.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]


In [268]:
denominator = np.outer(y.sum(axis=0), py.sum(axis=0))
print denominator

[[ 2.  1.  1.]
 [ 0.  0.  0.]
 [ 6.  3.  3.]]


In [269]:
denominator = denominator / np.sum(numerator)

In [270]:
numerator*w

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 1.,  1.,  0.]])

In [271]:
denominator*w

array([[ 0.  ,  0.25,  0.25],
       [ 0.  ,  0.  ,  0.  ],
       [ 1.5 ,  0.75,  0.  ]])

In [272]:
1 - (np.sum(numerator*w) / np.sum(denominator*w))

0.27272727272727271